import { Bagel_Fat_One } from "next/font/google";
import { League_Spartan } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";

import "./globals.css";
import { Suspense } from "react";

const bagel_fat_1 = Bagel_Fat_One({ subsets: ["latin"], weight: ["400"] });
const spartan_main_font = League_Spartan({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spartan_main_font.className}>
        <NextUIProvider>
          <Suspense>{children} </Suspense>
        </NextUIProvider>
      </body>
    </html>
  );
}
